server:
  port: 8084
  servlet:
    context-path: /api

spring:
  application:
    name: pagamento-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
