server:
  port: 8084
  servlet:
    context-path: /api

spring:
  application:
    name: pagamento-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pagamento}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    driver-class-name: "${SPRING_DATASOURCE_DRIVER-CLASS_NAME:org.postgresql.Driver}"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: false
    locations: classpath:db/migration

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
