server:
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: notificacao-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
