server:
  port: 8085
  servlet:
    context-path: /api

spring:
  application:
    name: notificacao-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
  virtual-host: /
  listener:
    simple:
      concurrency: 1
      max-concurrency: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
