global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'notificacao-service'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: [ 'notificacao:8081' ]

- job_name: 'pagamento-service'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: [ 'pagamento:8084' ]

- job_name: 'pedido-service'
  metrics_path: '/actuator/prometheus'
  static_configs:
  - targets: [ 'pedido:8083' ]
