# =================================================================
# ==     Blueprint do Render (render.yaml) para Microsserviços    ==
# =================================================================

databases:
- name: ms-postgres
  plan: free
  ipAllowList: []

services:
# === INFRAESTRUTURA ===
- type: private
  name: rabbitmq
  env: docker
  image:
    url: rabbitmq:4.1-management
  plan: free
  envVars:
  - fromGroup: app-secrets

- type: private
  name: eureka
  env: docker
  dockerContext: ./rsdesenvolvimento-api
  dockerfilePath: eureka-server/Dockerfile
  healthCheckPath: /actuator/health
  plan: free
  envVars:
  - key: EUREKA_INSTANCE_HOSTNAME
    value: eureka
  - key: EUREKA_CLIENT_REGISTER-WITH-EUREKA
    value: 'false'
  - key: EUREKA_CLIENT_FETCH-REGISTRY
    value: 'false'
  - key: SPRING_PROFILES_ACTIVE
    value: prod

- type: private
  name: keycloak
  env: docker
  image:
    url: bitnami/keycloak:26
  plan: free
  envVars:
  - fromGroup: app-secrets
  - key: KEYCLOAK_CREATE_ADMIN_USER
    value: 'true'
  - key: KEYCLOAK_DATABASE_VENDOR
    value: postgresql
  - key: KEYCLOAK_DATABASE_SCHEMA
    value: keycloak
  - key: KC_PROXY
    value: "edge"
  - key: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - key: KEYCLOAK_HTTP_RELATIVE_PATH
    value: /auth
  - key: KC_HOSTNAME_URL
    value: ${API_GATEWAY_URL}/auth
  - key: KEYCLOAK_DATABASE_HOST
    fromService: { type: psql, name: ms-postgres, property: host }
  - key: KEYCLOAK_DATABASE_PORT
    fromService: { type: psql, name: ms-postgres, property: port }
  - key: KEYCLOAK_DATABASE_NAME
    fromService: { type: psql, name: ms-postgres, property: database }
  - key: KEYCLOAK_DATABASE_USER
    fromService: { type: psql, name: ms-postgres, property: user }
  - key: KEYCLOAK_DATABASE_PASSWORD
    fromService: { type: psql, name: ms-postgres, property: password }

# === API GATEWAY (SERVIÇO PÚBLICO) ===
- type: web
  name: api-gateway
  env: docker
  dockerContext: ./rsdesenvolvimento-api
  dockerfilePath: api-gateway/Dockerfile
  healthCheckPath: /actuator/health
  plan: free
  envVars:
  - key: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
    value: http://eureka:8761/eureka/
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  - key: OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
    value: http://keycloak:8080/auth/realms/REALM_LOCAL

# === SERVIÇOS DE NEGÓCIO ===
- type: private
  name: pedido-service
  env: docker
  dockerContext: ./rsdesenvolvimento-api
  dockerfilePath: pedido-service/Dockerfile
  envVars:
  - fromGroup: app-secrets
  - key: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
    value: http://eureka:8761/eureka/
  - key: RABBITMQ_HOST
    value: rabbitmq
  - key: RABBITMQ_PORT
    value: '5672'
  - key: RABBITMQ_USERNAME
    value: guest
  - key: RABBITMQ_PASSWORD
    value: guest
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  - key: SPRING_DATASOURCE_URL
    fromService: { type: psql, name: ms-postgres, property: connectionString }
  - key: SPRING_DATASOURCE_USERNAME
    fromService: { type: psql, name: ms-postgres, property: user }
  - key: SPRING_DATASOURCE_PASSWORD
    fromService: { type: psql, name: ms-postgres, property: password }
  - key: FLYWAY_CREATE_SCHEMA
    value: 'true'
  - key: FLYWAY_ENABLED
    value: 'true'
  - key: FLYWAY_DEFAULT_SCHEMA
    value: pedido_adm
  - key: FLYWAY_SCHEMAS
    value: pedido,pedido_aud,pedido_adm
  - key: FLYWAY_LOCATIONS
    value: filesystem:/tmp/import
  - key: JPA_DIALECT
    value: org.hibernate.dialect.PostgreSQLDialect
  - key: JPA_SHOW_SQL
    value: 'true'
  - key: SERVER_PORT
    value: '8083'
  - key: CONTEXT_PATH
    value: /api
  - key: DEFAULT_LOCALE
    value: pt-BR
  - key: DEFAULT_TIMEZONE
    value: America/Belem
  - key: RESILIENCE4J_CIRCUITBREAKER_ESTOQUE_API_FAILURE_RATE_THRESHOLD
    value: '50'
  - key: RESILIENCE4J_CIRCUITBREAKER_ESTOQUE_API_SLOW_CALL_RATE_THRESHOLD
    value: '50'
  - key: RESILIENCE4J_CIRCUITBREAKER_ESTOQUE_API_WAIT_DURATION_IN_OPEN_STATE
    value: 10s
  - key: RESILIENCE4J_CIRCUITBREAKER_ESTOQUE_API_PERMITTED_CALLS_IN_HALF_OPEN
    value: '3'
  - key: RESILIENCE4J_CIRCUITBREAKER_ESTOQUE_API_MINIMUM_NUMBER_OF_CALLS
    value: '5'
  - key: RESILIENCE4J_RETRY_ESTOQUE_API_MAX_ATTEMPTS
    value: '3'
  - key: RESILIENCE4J_RETRY_ESTOQUE_API_WAIT_DURATION
    value: 2s
  - key: RESILIENCE4J_RETRY_ESTOQUE_API_EXPONENTIAL_BACKOFF_MULTIPLIER
    value: '2'
  - key: OAUTH2_RESOURCESERVER_JWK_SET_URI
    value: http://keycloak:8080/auth/realms/REALM_LOCAL/protocol/openid-connect/certs

- type: private
  name: notificacao-service
  env: docker
  dockerContext: ./rsdesenvolvimento-api
  dockerfilePath: notificacao-service/Dockerfile
  envVars:
  - fromGroup: app-secrets
  - key: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
    value: http://eureka:8761/eureka/
  - key: RABBITMQ_HOST
    value: rabbitmq
  - key: RABBITMQ_PORT
    value: '5672'
  - key: RABBITMQ_USERNAME
    value: guest
  - key: RABBITMQ_PASSWORD
    value: guest
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  - key: SPRING_DATASOURCE_URL
    fromService: { type: psql, name: ms-postgres, property: connectionString }
  - key: SPRING_DATASOURCE_USERNAME
    fromService: { type: psql, name: ms-postgres, property: user }
  - key: SPRING_DATASOURCE_PASSWORD
    fromService: { type: psql, name: ms-postgres, property: password }
  - key: SENDGRID_API_KEY
    value: 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
  - key: SERVER_PORT
    value: '8085'
  - key: CONTEXT_PATH
    value: /api
  - key: DEFAULT_LOCALE
    value: pt-BR
  - key: DEFAULT_TIMEZONE
    value: America/Belem

- type: private
  name: pagamento-service
  env: docker
  dockerContext: ./rsdesenvolvimento-api
  dockerfilePath: pagamento-service/Dockerfile
  envVars:
  - fromGroup: app-secrets
  - key: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
    value: http://eureka:8761/eureka/
  - key: RABBITMQ_HOST
    value: rabbitmq
  - key: RABBITMQ_PORT
    value: '5672'
  - key: RABBITMQ_USERNAME
    value: guest
  - key: RABBITMQ_PASSWORD
    value: guest
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  - key: SPRING_DATASOURCE_URL
    fromService: { type: psql, name: ms-postgres, property: connectionString }
  - key: SPRING_DATASOURCE_USERNAME
    fromService: { type: psql, name: ms-postgres, property: user }
  - key: SPRING_DATASOURCE_PASSWORD
    fromService: { type: psql, name: ms-postgres, property: password }
  - key: FLYWAY_CREATE_SCHEMA
    value: 'true'
  - key: FLYWAY_ENABLED
    value: 'true'
  - key: FLYWAY_DEFAULT_SCHEMA
    value: pagamento_adm
  - key: FLYWAY_SCHEMAS
    value: pagamento,pagamento_aud,pagamento_adm
  - key: FLYWAY_LOCATIONS
    value: filesystem:/tmp/import
  - key: JPA_DIALECT
    value: org.hibernate.dialect.PostgreSQLDialect
  - key: JPA_SHOW_SQL
    value: 'true'
  - key: SERVER_PORT
    value: '8084'
  - key: CONTEXT_PATH
    value: /api
  - key: DEFAULT_LOCALE
    value: pt-BR
  - key: DEFAULT_TIMEZONE
    value: America/Belem

- type: private
  name: estoque-api
  env: docker
  dockerContext: ./rsdesenvolvimento-api
  dockerfilePath: estoque/Dockerfile
  envVars:
  - fromGroup: app-secrets
  - key: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
    value: http://eureka:8761/eureka/
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  - key: SPRING_DATASOURCE_URL
    fromService: { type: psql, name: ms-postgres, property: connectionString }
  - key: SPRING_DATASOURCE_USERNAME
    fromService: { type: psql, name: ms-postgres, property: user }
  - key: SPRING_DATASOURCE_PASSWORD
    fromService: { type: psql, name: ms-postgres, property: password }
  - key: FLYWAY_CREATE_SCHEMA
    value: 'true'
  - key: FLYWAY_ENABLED
    value: 'true'
  - key: FLYWAY_DEFAULT_SCHEMA
    value: estoque_adm
  - key: FLYWAY_SCHEMAS
    value: estoque,estoque_aud,estoque_adm
  - key: FLYWAY_LOCATIONS
    value: filesystem:/tmp/import
  - key: ENVERS_SCHEMA
    value: estoque_aud
  - key: JPA_DIALECT
    value: org.hibernate.dialect.PostgreSQLDialect
  - key: JPA_SHOW_SQL
    value: 'true'
  - key: CLOUDINARY_CLOUD_NAME
    value: rsdesenvolvimento-estoque-api
  - key: CLOUDINARY_API_KEY
    value: '198152423354888'
  - key: CLOUDINARY_API_SECRET
    value: OT3yW8hP0Ytl47h-FWOHb11-kTE
  - key: SERVER_PORT
    value: '8082'
  - key: CONTEXT_PATH
    value: /api
  - key: DEFAULT_LOCALE
    value: pt-BR
  - key: DEFAULT_TIMEZONE
    value: America/Belem
