CREATE SEQUENCE IF NOT EXISTS SQ_PEDIDO START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE IF NOT EXISTS TB_PEDIDO (
    id BIGINT NOT NULL DEFAULT nextval('SQ_PEDIDO'),
    observacao VARCHAR(255),
    USUARIO_ID VARCHAR(255) NOT NULL,
    NOME_USUARIO VARCHAR(255) NOT NULL,
    EMAIL_USUARIO VARCHAR(255) NOT NULL,
    STATUS_PEDIDO VARCHAR(255),
    DATA_HORA_CRIACAO TIMESTAMP,
    CRIADO_POR VARCHAR(255),
    DATA_HORA_ATUALIZACAO TIMESTAMP,
    ATUALIZADO_POR VARCHAR(255),
      CONSTRAINT TB_PEDIDO_PK PRIMARY KEY (ID)
);



CREATE SEQUENCE IF NOT EXISTS SQ_ITEM_PEDIDO START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE IF NOT EXISTS TB_ITEM_PEDIDO (
    ID BIGINT NOT NULL DEFAULT nextval('SQ_ITEM_PEDIDO'),
    PEDIDO_ID BIGINT NOT NULL,
    PRODUTO_ID BIGINT NOT NULL,
    NOME_PRODUTO VARCHAR(255) NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    DATA_HORA_CRIACAO TIMESTAMP,
    CRIADO_POR VARCHAR(255),
    DATA_HORA_ATUALIZACAO TIMESTAMP,
    ATUALIZADO_POR VARCHAR(255),
    CONSTRAINT TB_ITEM_PEDIDO_PK PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO_ID FOREIGN KEY (PEDIDO_ID) REFERENCES TB_PEDIDO(ID)
    -- CONSTRAINT FK_PRODUTO_ID FOREIGN KEY (PRODUTO_ID) REFERENCES produto.TB_PRODUTO(ID)
);
