server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: usuario-api
  datasource:
    url: jdbc:postgresql://localhost:5432/usuario
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    repair: true
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
