server:
    port: 8080
    servlet:
        context-path: /api
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            default-filters:
                - >-
                    DedupeResponseHeader=Access-Control-Allow-Origin
                    Access-Control-Allow-Credentials
                - 'RewritePath=/{segment}/, /$1'
            globalcors:
                cors-configurations:
                    '[/**]': null
                allowedOrigins: '*'
                allowedMethods: '*'
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 10
