CREATE SEQUENCE IF NOT EXISTS SQ_ESTOQUE START WITH 1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE IF NOT EXISTS TB_ESTOQUE (
    ID BIGINT NOT NULL DEFAULT nextval('SQ_ESTOQUE'),
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    PRECO DECIMAL(10,2) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL,
    ESTOQUE INT DEFAULT 0,
    IMAGEM_URL VARCHAR(255),
    DATA_HORA_CRIACAO TIMESTAMP,
    CRIADO_POR VARCHAR(255),
    DATA_HORA_ATUALIZACAO TIMESTAMP,
    ATUALIZADO_POR VARCHAR(255),
    CONSTRAINT TB_ESTOQUE_PK PRIMARY KEY (ID)
);

ALTER TABLE TB_ESTOQUE DROP CONSTRAINT IF EXISTS TB_ESTOQUE_UK_ID;
ALTER TABLE TB_ESTOQUE ADD CONSTRAINT TB_ESTOQUE_UK_ID UNIQUE (ID);


-- Inserir registros iniciais
INSERT INTO TB_ESTOQUE (ID, NOME, DESCRICAO, PRECO, CATEGORIA, ESTOQUE, IMAGEM_URL,
                        DATA_HORA_CRIACAO, CRIADO_POR)
VALUES (1, 'Produto 1', 'Descrição do produto 1', 29.99, 'PRATO PRINCIPAL', 100,
        'https://example.com/produto1.jpg', CURRENT_TIMESTAMP, 'TESTE');

INSERT INTO TB_ESTOQUE (ID, NOME, DESCRICAO, PRECO, CATEGORIA, ESTOQUE, IMAGEM_URL,
                        DATA_HORA_CRIACAO, CRIADO_POR)
VALUES (2, 'Produto 2', 'Descrição do produto 2', 49.99, 'SOBREMESA', 50,
        'https://example.com/produto2.jpg', CURRENT_TIMESTAMP, 'TESTE');

INSERT INTO TB_ESTOQUE (ID, NOME, DESCRICAO, PRECO, CATEGORIA, ESTOQUE, IMAGEM_URL,
                        DATA_HORA_CRIACAO, CRIADO_POR)
VALUES (3, 'Produto 3', 'Descrição do produto 3', 19.99, 'PRATO PRINCIPAL', 200,
        'https://example.com/produto3.jpg', CURRENT_TIMESTAMP, 'TESTE');

ALTER SEQUENCE SQ_ESTOQUE RESTART WITH 4;
