SET SCHEMA 'pagamento';

-- [SEQUENCE:PAGAMENTO]
CREATE SEQUENCE IF NOT EXISTS SQ_PAGAMENTO START
 WITH
     1 INCREMENT BY 1 MINVALUE 1;

-- [TABLE:PAGAMENTO]
CREATE TABLE IF NOT EXISTS pagamento.TB_PAGAMENTO(
    ID BIGINT NOT NULL DEFAULT nextval('SQ_PAGAMENTO'),
    PEDIDO_ID BIGINT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DATA_HORA_CRIACAO TIMESTAMP,
    CRIADO_POR VARCHAR(255),
    DATA_HORA_ATUALIZACAO TIMESTAMP,
    ATUALIZADO_POR VARCHAR(255),
      CONSTRAINT TB_PAGAMENTO_PK PRIMARY KEY (ID)
);

-- [CONSTRAINTS:PAGAMENTO]
ALTER TABLE TB_PAGAMENTO
    DROP CONSTRAINT IF EXISTS TB_PAGAMENTO_UK_PEDIDO_ID;

ALTER TABLE TB_PAGAMENTO
    ADD CONSTRAINT TB_PAGAMENTO_UK_PEDIDO_ID UNIQUE (PEDIDO_ID);



