-- [SEQUENCE:PAGAMENTO]
CREATE SEQUENCE IF NOT EXISTS SQ_PAGAMENTO START WITH 1 INCREMENT BY 1 MINVALUE 1;

-- [TABLE:PAGAMENTO]
CREATE TABLE IF NOT EXISTS TB_PAGAMENTO(
    ID BIGINT NOT NULL DEFAULT nextval('SQ_PAGAMENTO'),
    PEDIDO_ID BIGINT NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DATA_HORA_CRIACAO TIMESTAMP,
    CRIADO_POR VARCHAR(255),
    DATA_HORA_ATUALIZACAO TIMESTAMP,
    ATUALIZADO_POR VARCHAR(255),
      CONSTRAINT TB_PAGAMENTO_PK PRIMARY KEY (ID)
);

-- [CONSTRAINTS:PAGAMENTO]
ALTER TABLE TB_PAGAMENTO
    DROP CONSTRAINT IF EXISTS TB_PAGAMENTO_UK_PEDIDO_ID;

ALTER TABLE TB_PAGAMENTO
    ADD CONSTRAINT TB_PAGAMENTO_UK_PEDIDO_ID UNIQUE (PEDIDO_ID);


INSERT INTO TB_PAGAMENTO (ID, PEDIDO_ID, VALOR, DATA_HORA, STATUS, DATA_HORA_CRIACAO, CRIADO_POR)
VALUES (1, 1, 99.99, CURRENT_TIMESTAMP, 'PENDENTE', CURRENT_TIMESTAMP, 'TESTE');

INSERT INTO TB_PAGAMENTO (ID, PEDIDO_ID, VALOR, DATA_HORA, STATUS, DATA_HORA_CRIACAO, CRIADO_POR)
VALUES (2, 2, 49.99, CURRENT_TIMESTAMP, 'EM_ANDAMENTO', CURRENT_TIMESTAMP, 'TESTE');

INSERT INTO TB_PAGAMENTO (ID, PEDIDO_ID, VALOR, DATA_HORA, STATUS, DATA_HORA_CRIACAO, CRIADO_POR)
VALUES (3, 3, 49.99, CURRENT_TIMESTAMP, 'FINALIZADO', CURRENT_TIMESTAMP, 'TESTE');

INSERT INTO TB_PAGAMENTO (ID, PEDIDO_ID, VALOR, DATA_HORA, STATUS, DATA_HORA_CRIACAO, CRIADO_POR)
VALUES (4, 4, 59.99, CURRENT_TIMESTAMP, 'FINALIZADO', CURRENT_TIMESTAMP, 'TESTE');

INSERT INTO TB_PAGAMENTO (ID, PEDIDO_ID, VALOR, DATA_HORA, STATUS, DATA_HORA_CRIACAO, CRIADO_POR)
VALUES (5, 5, 19.99, CURRENT_TIMESTAMP, 'CANCELADO', CURRENT_TIMESTAMP, 'TESTE');


ALTER SEQUENCE SQ_PAGAMENTO RESTART WITH 6;
