SET SCHEMA 'pedido';

-- [SEQUENCE:PEDIDO]
CREATE SEQUENCE IF NOT EXISTS SQ_PEDIDO START 
WITH
     1 INCREMENT BY 1 MINVALUE 1;

-- [TABLE:PEDIDO]
CREATE TABLE IF NOT EXISTS pedido.TB_PEDIDO (
    id BIGINT NOT NULL DEFAULT nextval('SQ_PEDIDO'),
    DESCRICAO VARCHAR(255),
    USUARIO_ID BIGINT NOT NULL,
    NOME_USUARIO VARCHAR(255) NOT NULL,
    EMAIL_USUARIO VARCHAR(255) NOT NULL UNIQUE,
    STATUS_PEDIDO VARCHAR(255),
    DATA_HORA_CRIACAO TIMESTAMP,
    CRIADO_POR VARCHAR(255),
    DATA_HORA_ATUALIZACAO TIMESTAMP,
    ATUALIZADO_POR VARCHAR(255),
      CONSTRAINT TB_PEDIDO_PK PRIMARY KEY (ID)
);

-- [CONSTRAINTS:PEDIDO]
ALTER TABLE TB_PEDIDO
    DROP CONSTRAINT IF EXISTS TB_PEDIDO_UK_EMAIL_USUARIO;

ALTER TABLE TB_PEDIDO
    ADD CONSTRAINT TB_PEDIDO_UK_EMAIL_USUARIO UNIQUE (EMAIL_USUARIO);        