
SET SCHEMA 'pedido_aud';
-----------------
------ AUDITORIA
-----------------

CREATE SEQUENCE IF NOT EXISTS REVINFO_SEQ AS BIGINT start 
with 
   1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE IF NOT EXISTS REVINFO (
  id integer not null, timestamp bigint, pedido varchar(255), primary key (id));

--[TABLE: PEDIDO]

CREATE TABLE IF NOT EXISTS TB_PEDIDO_AUD AS TABLE pedido.TB_PEDIDO 
WITH NO DATA;

ALTER TABLE TB_PEDIDO_AUD ADD COLUMN REV INTEGER NOT NULL;
ALTER TABLE TB_PEDIDO_AUD ADD COLUMN REVTYPE SMALLINT;

--[CONSTRAINT]
ALTER TABLE TB_PEDIDO_AUD
  ADD CONSTRAINT TB_PEDIDO_AUD_FK_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (ID);