ALTER TABLE pedido.TB_PEDIDO
    DROP CONSTRAINT IF EXISTS TB_PEDIDO_UK_EMAIL_USUARIO;

ALTER TABLE pedido.TB_PEDIDO
    ALTER COLUMN EMAIL_USUARIO DROP NOT NULL,
    ALTER COLUMN EMAIL_USUARIO SET NOT NULL;
