SET SCHEMA 'pedido';

CREATE SEQUENCE IF NOT EXISTS SQ_ITEM_PEDIDO START
WITH
     1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE IF NOT EXISTS TB_ITEM_PEDIDO (
    ID BIGINT NOT NULL DEFAULT nextval('SQ_ITEM_PEDIDO'),
    PEDIDO_ID BIGINT NOT NULL,
    PRODUTO_ID BIGINT NOT NULL,
    NOME_PRODUTO VARCHAR(255) NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO_UNITARIO DECIMAL(10, 2) NOT NULL,
    DATA_HORA_CRIACAO TIMESTAMP,
    CRIADO_POR VARCHAR(255),
    DATA_HORA_ATUALIZACAO TIMESTAMP,
    ATUALIZADO_POR VARCHAR(255),
    CONSTRAINT TB_ITEM_PEDIDO_PK PRIMARY KEY (ID),
    CONSTRAINT FK_PEDIDO_ID FOREIGN KEY (PEDIDO_ID) REFERENCES pedido.TB_PEDIDO(ID)
    -- CONSTRAINT FK_PRODUTO_ID FOREIGN KEY (PRODUTO_ID) REFERENCES produto.TB_PRODUTO(ID)
);

-----------------
------ AUDITORIA
-----------------
CREATE SCHEMA IF NOT EXISTS item_pedido_aud;
SET SCHEMA 'item_pedido_aud';

CREATE TABLE IF NOT EXISTS REVINFO (
  id integer not null,
  timestamp bigint,
  pedido varchar(255),
  primary key (id)
);

--[TABLE: ITEM_PEDIDO]
CREATE TABLE IF NOT EXISTS TB_ITEM_PEDIDO_AUD AS TABLE pedido.TB_ITEM_PEDIDO
WITH NO DATA;

ALTER TABLE TB_ITEM_PEDIDO_AUD ADD COLUMN REV INTEGER NOT NULL;
ALTER TABLE TB_ITEM_PEDIDO_AUD ADD COLUMN REVTYPE SMALLINT;

--[CONSTRAINT]
ALTER TABLE IF EXISTS TB_ITEM_PEDIDO_AUD
  ADD CONSTRAINT TB_ITEM_PEDIDO_AUD_FK_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (ID);
