SET SCHEMA 'pedido_aud';

CREATE TABLE IF NOT EXISTS TB_ITEM_PEDIDO_AUD AS TABLE pedido.TB_ITEM_PEDIDO
WITH NO DATA;

ALTER TABLE TB_ITEM_PEDIDO_AUD ADD COLUMN IF NOT EXISTS REV INTEGER NOT NULL;
ALTER TABLE TB_ITEM_PEDIDO_AUD ADD COLUMN IF NOT EXISTS REVTYPE SMALLINT;

ALTER TABLE TB_ITEM_PEDIDO_AUD
  ADD CONSTRAINT TB_ITEM_PEDIDO_AUD_FK_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (ID);
