server:
  port: 8083
  servlet:
    context-path: /api
spring:
  application:
    name: pedido-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pedido
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.rsdesenvolvimento.pedido_service.core.client: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
