server:
  port: 8083
  servlet:
    context-path: /api
spring:
  application:
    name: pedido-service
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pedido}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
    driver-class-name: "${SPRING_DATASOURCE_DRIVER-CLASS_NAME:org.postgresql.Driver}"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    baseline-on-migrate: true
    out-of-order: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}"
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
resilience4j:
  circuitbreaker:
    instances:
      usuario-api:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5 # Avalia últimas 5 chamadas
        slowCallRateThreshold: 50 # Aciona o circuito se as chamadas lentas excederem 50%
        failureRateThreshold: 50 # Aciona o circuito se as falhas excederem 50%
        minimumNumberOfCalls: 5 # Chamadas mínimas antes de avaliar o circuito
        waitDurationInOpenState: 10s # Aguarde 10s antes de passar para o estado meio aberto
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - java.net.UnknownHostException
          - java.net.ConnectException
          - org.springframework.web.client.HttpServerErrorException
          - feign.RetryableException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
  retry:
    instances:
      usuario-api:
        maxAttempts: 3
        waitDuration: 2s
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpClientErrorException
          - java.net.UnknownHostException
          - java.net.ConnectException
          - feign.RetryableException

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
logging:
  level:
    com.rsdesenvolvimento.pedido_service.core.client: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j: DEBUG
