server:
    port: ${SERVER_PORT:8085}
    servlet:
        context-path: ${CONTEXT_PATH:/api}

spring:
    application:
        name: notificacao-service
    rabbitmq:
        host: ${RABBITMQ_HOST:localhost}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USERNAME:guest}
        password: ${RABBITMQ_PASSWORD:guest}
        virtual-host: /
        listener:
            simple:
                concurrency: 1
                max-concurrency: 10
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
        endpoint:
            health:
                probes:
                    enabled: true
sendgrid:
    api:
        # key: ${SENDGRID_API_KEY}
        key: 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

logging:
    level:
        org.springframework.amqp: DEBUG
        org.springframework.amqp.rabbit: DEBUG
        org.springframework.amqp.rabbit.core: DEBUG
        org.springframework.amqp.rabbit.listener: DEBUG
        org.springframework.amqp.rabbit.connection: DEBUG

        com.rabbitmq.client: DEBUG

        com.sendgrid: DEBUG
