server:
    port: ${SERVER_PORT:8082}
    servlet:
        context-path: ${CONTEXT_PATH:/api}
spring:
    servlet:
        multipart:
            max-file-size: ${MAX_FILE_UPLOAD_SIZE:5MB}
            max-request-size: ${MAX_REQUEST_SIZE:10MB}

    profiles:
        active:
            - '@activatedProfile@'
    application:
        name: estoque-api
    flyway:
        enabled: ${FLYWAY_ENABLED:false}
        baseline-on-migrate: true
        baseline-version: 0
        baseline-description: Estoque Baseline
        create-schemas: ${FLYWAY_CREATE_SCHEMA:false}
        default-schema: ${FLYWAY_DEFAULT_SCHEMA:estoque_adm}
        schemas: ${FLYWAY_SCHEMAS:estoque,estoque_aud, estoque_adm}
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/estoque}
        user: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:postgres}
        locations: ${FLYWAY_LOCATIONS:classpath:db/migration,classpath:db/data/dev}
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/estoque}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:postgres}
        driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS_NAME:org.postgresql.Driver}
    h2:
        console:
            enabled: false
    jpa:
        database-platform: ${JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        hibernate:
            ddl-auto: none
        open-in-view: false
        show-sql: ${JPA_SHOW_SQL:false}
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
                format_sql: ${JPA_FORMAT_SQL:false}
                default_schema: ${DB_SCHEMA:"estoque"}
            org:
                hibernate:
                    envers:
                        default_schema: ${ENVERS_SCHEMA:"estoque_aud"}
            javax.persistence.schema-generation.scripts:
                action: none
    sql:
        init:
            mode: never
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
    instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 10

management:
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
        endpoint:
            health:
                probes:
                    enabled: true

cloudinary:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
    api_secret: ${CLOUDINARY_API_SECRET}

    # Descomentar para rodar o SonarQube
# cloudinary:
#     cloud_name: rsdesenvolvimento-estoque-api
#     api_key: 198152423354888
#     api_secret: OT3yW8hP0Ytl47h-FWOHb11-kTE
---
################################################
# configurações específicas para profile LOCAL #
################################################

spring:
    config:
        activate:
            on-profile: local
    flyway:
        enabled: true
        cleanDisabled: false
        create-schemas: true
        url: jdbc:postgresql://localhost:5432/estoque
        user: postgres
        password: postgres
        locations: ${FLYWAY_LOCATIONS:classpath:db/migration,classpath:db/data/dev}
    datasource:
        url: jdbc:postgresql://localhost:5432/estoque
        username: postgres
        password: postgres
    jpa:
        # show-sql: true
        properties:
            hibernate:
                format_sql: true
            javax.persistence.schema-generation.scripts:
                action: drop-and-create
                create-source: metadata
                create-target: target/create.sql
                drop-source: metadata
                drop-target: target/drop.sql
# configurações de logging
logging:
    level:
        org:
            flywaydb: debug
            hibernate:
                type.descriptor.sql.BasicBinder: info
            springframework:
                web:
                    filter: info
                    client: debug
                transaction: error
