global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'notificacao-service'
  metrics_path: 'api/actuator/prometheus'
  static_configs:
  - targets: [ 'notificacao-service:8085' ]

- job_name: 'pagamento-service'
  metrics_path: 'api/actuator/prometheus'
  static_configs:
  - targets: [ 'pagamento-service:8084' ]

- job_name: 'pedido-service'
  metrics_path: 'api/actuator/prometheus'
  static_configs:
  - targets: [ 'pedido-service:8083' ]
