
SET SCHEMA 'usuario_aud';
-----------------
------ AUDITORIA
-----------------

CREATE SEQUENCE IF NOT EXISTS REVINFO_SEQ AS BIGINT start 
with 
   1 INCREMENT BY 1 MINVALUE 1;

CREATE TABLE IF NOT EXISTS REVINFO (
  id integer not null, timestamp bigint, usuario varchar(255), primary key (id));

--[TABLE: USUARIO]

CREATE TABLE IF NOT EXISTS TB_USUARIO_AUD AS TABLE usuario.TB_USUARIO 
WITH NO DATA;

ALTER TABLE TB_USUARIO_AUD ADD COLUMN REV INTEGER NOT NULL;
ALTER TABLE TB_USUARIO_AUD ADD COLUMN REVTYPE SMALLINT;

--[CONTRAINT]
ALTER TABLE TB_USUARIO_AUD
  ADD CONSTRAINT TB_USUARIO_AUD_FK_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO (ID);